# CI de Nivel 04 - Disparo dos testes dentro do pipe de dev

name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Checando padronização do código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando testes de unidade com cobertura
        run: yarn coverage

      - name: Upload do relatório de cobertura
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cobertura
          path: reports/coverage/lcov-report

  deploy:
    runs-on: ubuntu-latest
    needs: [unidade]

    steps:
      - name: Simulação do Deploy
        run: echo "simulando o deploy com sucesso"
